import { promises as fs } from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import type { MetadataRoute } from "next";
import { absoluteUrl, publicRoutes } from "@/lib/sitemap";

// Serves https://www.gphusa.com/sitemap.xml.
//
// No dynamic APIs are touched, so Next prerenders this at build time: the file
// is regenerated by every `npm run build`, which is what makes a new help
// article or product page show up without anyone remembering to run anything.
// WHICH urls appear, and their fallback dates, live in src/lib/sitemap.ts —
// this file only resolves <lastmod> and formats the XML.
//
// One flat sitemap, not a sitemap index: the protocol's limits are 50,000 URLs
// and 50 MB, and we publish a few dozen. Split it only if the public surface
// ever grows by three orders of magnitude.

/** Content roots whose frontmatter may carry a `last_updated`. */
const MARKDOWN_ROOTS: Record<string, string> = {
  "/help/": path.join(process.cwd(), "src", "content", "help"),
  "/legal/": path.join(process.cwd(), "src", "content", "legal"),
};

/**
 * gray-matter hands back whatever YAML parsed: `last_updated: "2026-08-20"` is
 * a string, the same line unquoted is a Date. Normalise both to YYYY-MM-DD and
 * reject anything else, so a typo in frontmatter drops the date rather than
 * emitting an invalid <lastmod> that invalidates the entry for a validator.
 */
function toIsoDate(value: unknown): string | undefined {
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    return value.toISOString().slice(0, 10);
  }
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed) && !Number.isNaN(Date.parse(trimmed))) {
      return trimmed;
    }
  }
  return undefined;
}

/**
 * The `last_updated` in a page's own markdown, when it has one. This is the
 * date the article itself displays, so the sitemap and the byline can never
 * disagree — and an editor updating copy bumps both in one edit.
 */
async function frontmatterLastmod(routePath: string): Promise<string | undefined> {
  const prefix = Object.keys(MARKDOWN_ROOTS).find((p) => routePath.startsWith(p));
  if (!prefix) return undefined;

  const slug = routePath.slice(prefix.length);
  // Guard the path join: slugs come from our own registries today, but this is
  // the one place they become a filename.
  if (!/^[a-z0-9-]+$/.test(slug)) return undefined;

  try {
    const raw = await fs.readFile(path.join(MARKDOWN_ROOTS[prefix], `${slug}.md`), "utf8");
    return toIsoDate(matter(raw).data.last_updated);
  } catch {
    // /legal/cookies and any future hand-built page under these prefixes have
    // no markdown file. Fall back to the registry date.
    return undefined;
  }
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const routes = publicRoutes();

  return Promise.all(
    routes.map(async (route) => {
      const lastModified = (await frontmatterLastmod(route.path)) ?? route.lastmod;
      return {
        url: absoluteUrl(route.path),
        // Omitted entirely when undated — <lastmod> is optional, and a made-up
        // date (the build timestamp, say) would mark the whole site as changed
        // on every deploy and get the signal discounted.
        ...(lastModified ? { lastModified } : {}),
        changeFrequency: route.changeFrequency,
        priority: route.priority,
      };
    }),
  );
}
